using Xunit;

namespace Repro.LocalizationAndAuthGuard.EntityFrameworkCore;

[CollectionDefinition(LocalizationAndAuthGuardTestConsts.CollectionDefinitionName)]
public class LocalizationAndAuthGuardEntityFrameworkCoreCollection : ICollectionFixture<LocalizationAndAuthGuardEntityFrameworkCoreFixture>
{

}
