using Volo.Abp;

namespace Repro.LocalizationAndAuthGuard.EntityFrameworkCore;

public abstract class LocalizationAndAuthGuardEntityFrameworkCoreTestBase : LocalizationAndAuthGuardTestBase<LocalizationAndAuthGuardEntityFrameworkCoreTestModule>
{

}
